// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	IP                   string   `protobuf:"bytes,1,opt,name=iP,proto3" json:"iP,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Master               string   `protobuf:"bytes,4,opt,name=master,proto3" json:"master,omitempty"`
	ControllerIP         string   `protobuf:"bytes,5,opt,name=controllerIP,proto3" json:"controllerIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *RegisterReq) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RegisterReq) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *RegisterReq) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *RegisterReq) GetControllerIP() string {
	if m != nil {
		return m.ControllerIP
	}
	return ""
}

type RegisterResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type KeepAliveReq struct {
	IP                   string   `protobuf:"bytes,1,opt,name=iP,proto3" json:"iP,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	CpuUsage             string   `protobuf:"bytes,3,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemUsage             string   `protobuf:"bytes,4,opt,name=memUsage,proto3" json:"memUsage,omitempty"`
	DnsAlive             bool     `protobuf:"varint,5,opt,name=dnsAlive,proto3" json:"dnsAlive,omitempty"`
	DhcpAlive            bool     `protobuf:"varint,6,opt,name=dhcpAlive,proto3" json:"dhcpAlive,omitempty"`
	Master               string   `protobuf:"bytes,7,opt,name=Master,proto3" json:"Master,omitempty"`
	ControllerIP         string   `protobuf:"bytes,8,opt,name=controllerIP,proto3" json:"controllerIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveReq) Reset()         { *m = KeepAliveReq{} }
func (m *KeepAliveReq) String() string { return proto.CompactTextString(m) }
func (*KeepAliveReq) ProtoMessage()    {}
func (*KeepAliveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{2}
}

func (m *KeepAliveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveReq.Unmarshal(m, b)
}
func (m *KeepAliveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveReq.Marshal(b, m, deterministic)
}
func (m *KeepAliveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveReq.Merge(m, src)
}
func (m *KeepAliveReq) XXX_Size() int {
	return xxx_messageInfo_KeepAliveReq.Size(m)
}
func (m *KeepAliveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveReq.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveReq proto.InternalMessageInfo

func (m *KeepAliveReq) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *KeepAliveReq) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *KeepAliveReq) GetCpuUsage() string {
	if m != nil {
		return m.CpuUsage
	}
	return ""
}

func (m *KeepAliveReq) GetMemUsage() string {
	if m != nil {
		return m.MemUsage
	}
	return ""
}

func (m *KeepAliveReq) GetDnsAlive() bool {
	if m != nil {
		return m.DnsAlive
	}
	return false
}

func (m *KeepAliveReq) GetDhcpAlive() bool {
	if m != nil {
		return m.DhcpAlive
	}
	return false
}

func (m *KeepAliveReq) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *KeepAliveReq) GetControllerIP() string {
	if m != nil {
		return m.ControllerIP
	}
	return ""
}

type KeepAliveResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResp) Reset()         { *m = KeepAliveResp{} }
func (m *KeepAliveResp) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResp) ProtoMessage()    {}
func (*KeepAliveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{3}
}

func (m *KeepAliveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResp.Unmarshal(m, b)
}
func (m *KeepAliveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResp.Marshal(b, m, deterministic)
}
func (m *KeepAliveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResp.Merge(m, src)
}
func (m *KeepAliveResp) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResp.Size(m)
}
func (m *KeepAliveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResp.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResp proto.InternalMessageInfo

func (m *KeepAliveResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *KeepAliveResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "proto.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "proto.RegisterResp")
	proto.RegisterType((*KeepAliveReq)(nil), "proto.KeepAliveReq")
	proto.RegisterType((*KeepAliveResp)(nil), "proto.KeepAliveResp")
}

func init() { proto.RegisterFile("monitor.proto", fileDescriptor_44174b7b2a306b71) }

var fileDescriptor_44174b7b2a306b71 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4f, 0xb3, 0x40,
	0x14, 0xfc, 0x80, 0xaf, 0x2d, 0x3c, 0xdb, 0xc6, 0x3c, 0x1b, 0xb3, 0x21, 0x1e, 0x1a, 0x4e, 0x3d,
	0xf5, 0xa0, 0x31, 0x31, 0x7a, 0xf2, 0x68, 0x0c, 0xa6, 0x21, 0xf1, 0x07, 0x20, 0x7d, 0xa1, 0x24,
	0x2c, 0x8b, 0xbb, 0xd4, 0xbb, 0x67, 0xff, 0xa5, 0xbf, 0xc4, 0xec, 0x6e, 0xa1, 0x98, 0x72, 0xf1,
	0x04, 0x33, 0xf3, 0x76, 0x77, 0x66, 0xf2, 0x60, 0xc6, 0x45, 0x55, 0x34, 0x42, 0xae, 0x6b, 0x29,
	0x1a, 0x81, 0x23, 0xf3, 0x89, 0xbe, 0x1c, 0x38, 0x4b, 0x28, 0x2f, 0x54, 0x43, 0x32, 0xa1, 0x77,
	0x9c, 0x83, 0x5b, 0x6c, 0x98, 0xb3, 0x74, 0x56, 0x41, 0xe2, 0x16, 0x1b, 0x0c, 0xc1, 0xdf, 0x09,
	0xd5, 0xbc, 0xa4, 0x9c, 0x98, 0x6b, 0xd8, 0x0e, 0xe3, 0x02, 0x46, 0x52, 0x94, 0xa4, 0x98, 0xb7,
	0xf4, 0x56, 0x41, 0x62, 0x01, 0x5e, 0xc2, 0x98, 0xa7, 0xfa, 0x3a, 0xf6, 0xdf, 0xcc, 0x1f, 0x10,
	0x46, 0x30, 0xcd, 0x44, 0xd5, 0x48, 0x51, 0x96, 0x24, 0x9f, 0x36, 0x6c, 0x64, 0xd4, 0x5f, 0x5c,
	0x74, 0x0f, 0xd3, 0xa3, 0x19, 0x55, 0x23, 0x83, 0x89, 0xda, 0x67, 0x19, 0x29, 0x65, 0x2c, 0xf9,
	0x49, 0x0b, 0xf1, 0x1c, 0x3c, 0xae, 0xf2, 0x83, 0x25, 0xfd, 0x1b, 0x7d, 0x3b, 0x30, 0x7d, 0x26,
	0xaa, 0x1f, 0xcb, 0xe2, 0x83, 0x86, 0xa2, 0x74, 0x76, 0xdd, 0xbe, 0xdd, 0x10, 0xfc, 0xac, 0xde,
	0xbf, 0xaa, 0x34, 0x27, 0xe6, 0xd9, 0x80, 0x2d, 0xd6, 0x1a, 0x27, 0x6e, 0x35, 0x1b, 0xa6, 0xc3,
	0x5a, 0xdb, 0x56, 0xca, 0x3c, 0x66, 0xa2, 0xf8, 0x49, 0x87, 0xf1, 0x0a, 0x82, 0xed, 0x2e, 0xb3,
	0x4e, 0xd8, 0xd8, 0x88, 0x47, 0x42, 0x17, 0x14, 0xdb, 0x82, 0x26, 0xb6, 0xa0, 0x78, 0xb8, 0x20,
	0x7f, 0xa0, 0xa0, 0x07, 0x98, 0xf5, 0x32, 0xfe, 0xad, 0xa1, 0xeb, 0x4f, 0x07, 0xe6, 0xb1, 0x5d,
	0x82, 0x38, 0xad, 0xd2, 0x9c, 0x24, 0xde, 0x82, 0xdf, 0x16, 0x8e, 0x68, 0x37, 0x63, 0xdd, 0x5b,
	0x87, 0xf0, 0xe2, 0x84, 0x53, 0x75, 0xf4, 0x0f, 0xef, 0x20, 0xe8, 0x6c, 0x60, 0x3b, 0xd3, 0x2f,
	0x3f, 0x5c, 0x9c, 0x92, 0xfa, 0xe4, 0xdb, 0xd8, 0xd0, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x90, 0xe3, 0xa9, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorManagerClient is the client API for MonitorManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorManagerClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	KeepAlive(ctx context.Context, in *KeepAliveReq, opts ...grpc.CallOption) (*KeepAliveResp, error)
}

type monitorManagerClient struct {
	cc *grpc.ClientConn
}

func NewMonitorManagerClient(cc *grpc.ClientConn) MonitorManagerClient {
	return &monitorManagerClient{cc}
}

func (c *monitorManagerClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/proto.MonitorManager/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorManagerClient) KeepAlive(ctx context.Context, in *KeepAliveReq, opts ...grpc.CallOption) (*KeepAliveResp, error) {
	out := new(KeepAliveResp)
	err := c.cc.Invoke(ctx, "/proto.MonitorManager/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorManagerServer is the server API for MonitorManager service.
type MonitorManagerServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	KeepAlive(context.Context, *KeepAliveReq) (*KeepAliveResp, error)
}

// UnimplementedMonitorManagerServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorManagerServer struct {
}

func (*UnimplementedMonitorManagerServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedMonitorManagerServer) KeepAlive(ctx context.Context, req *KeepAliveReq) (*KeepAliveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}

func RegisterMonitorManagerServer(s *grpc.Server, srv MonitorManagerServer) {
	s.RegisterService(&_MonitorManager_serviceDesc, srv)
}

func _MonitorManager_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorManagerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MonitorManager/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorManagerServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorManager_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorManagerServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MonitorManager/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorManagerServer).KeepAlive(ctx, req.(*KeepAliveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MonitorManager",
	HandlerType: (*MonitorManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _MonitorManager_Register_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _MonitorManager_KeepAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}
